name: Deploy Weed Detection App
on:
  push:
    branches: [ master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools

      - name: Get Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
  
      - name: Create ECR Repository
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: "mtech-pest-detection"
  
      - name: Push Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            058264444462.dkr.ecr.us-east-1.amazonaws.com/mtech-pest-detection:latest
            058264444462.dkr.ecr.us-east-1.amazonaws.com/mtech-pest-detection:${{ github.sha }}
      
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: pest-detection-fargate
          template: ./cloudformation/ecs-service.yml
          no-fail-on-empty-changeset: "1"
      
      # - name: Force CloudFormation Update
      #   run: |
      #       aws cloudformation update-stack --stack-name pest-detection-fargate --template-body file://cloudformation/ecs-service.yml  --capabilities CAPABILITY_IAM
  